{% set version = "1.7.1" %}
{% set number = 2 %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}
{% if cuda_compiler_version != "None" %}
{% set number = number + 200 %}
{% endif %}

package:
  name: mmcv-recipe
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmcv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8a2a16ee99b436d9506fe393d09ab17f0209ba8d27d785f3c94c4c3f97e97123
build:
  number: {{ number }}
  skip: true  # [win]
  # as of pytorch 1.13, conda-forge only builds for CUDA 11.2+, see
  # https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3491
  skip: true  # [cuda_compiler_version in ("10.2", "11.0", "11.1")]

outputs:
  - name: mmcv-full
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: false
      run_exports:
        - {{ pin_subpackage('mmcv-full', max_pin='x.x') }}
      missing_dso_whitelist:
        # conda-forge::pytorch provides these libs
        - $RPATH/libc10_cuda.so
        - $RPATH/libtorch_python.so
        - $RPATH/libtorch_cpu.so
        - $RPATH/libc10.so
        - $RPATH/libc10_cuda.dylib
        - $RPATH/libtorch_python.dylib
        - $RPATH/libtorch_cpu.dylib
        - $RPATH/libc10.dylib
    script: build_mmcv.sh  # [not win]
    requirements:
      build:
        - cross-python_{{ target_platform }}                   # [build_platform != target_platform]
        - ninja
        - numpy                                                # [build_platform != target_platform]
        - python                                               # [build_platform != target_platform]
        - pytorch                                              # [build_platform != target_platform]
        - pytorch ={{ pytorch }}={{ torch_proc_type }}*        # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # this adds matching cuda requirement to run deps using __cuda package
        - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
      host:
        - future
        - numpy
        - pip
        - pkg-config  # [unix]
        - py-opencv
        - python
        - pytorch
        - pytorch ={{ pytorch }}={{ torch_proc_type }}*
        - requests
        - setuptools
        - six
        - torchvision
        - typing
        - typing_extensions
      run:
        # intentionally skipping opencv and pytorch (following upstream vendor)
        - __cuda  # [cuda_compiler_version != "None"]
        - addict
        - {{ pin_compatible('numpy') }}
        - packaging
        - Pillow
        - pyyaml
        - typing_extensions
        - yapf
      run_constrained:
        # additional run constraint to the one from the (version-only) run_export;
        # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
        - pytorch =*={{ torch_proc_type }}*

    test:
      requires:
        - pytest
        - requests
        - scipy
        - libopencv
        - py-opencv
        - opencv
        - python-lmdb
        - libiconv
        - tifffile
        - python-dateutil
        - torchvision
      imports:
        - mmcv
      source_files:
        - tests
      commands:
        {% set failing_tests = ["test_digit_version",
                                "test_imcrop",
                                "test_tensor2imgs",
                                "test_imwrite",
                                "test_imfrombytes",
                                "test_imread"] %}
        {% set slow_tests = ["test_eval_hook",
                             "test_start_param",
                             "test_flat_cosine_runner_hook",
                             "test_momentum_runner_hook",
                             "test_step_runner_hook",
                             "test_adjust_sharpness",
                             "test_adjust_contrast",
                             "test_adjust_brightness",
                             "test_gradient_cumulative_optimizer_hook",
                             "test_auto_contrast"] %}
        {% set ignored_files = ["./tests/test_ops/test_onnx.py",
                                "./tests/test_ops/test_tensorrt.py",
                                "./tests/test_ops/test_tensorrt_preprocess.py",
                                "./tests/test_utils/test_timer.py",
                                "./tests/test_utils/test_progressbar.py"] %}
        # ignored tests:
        # test_onnx.py,test_tensorrt.py,test_tensorrt_preprocess.py - mccv currently compiled without onnx runtime
        # test_geometric.py:test_imcrop - depending on what backend opencv uses it produces diff results (lipjpeg vs libturbojpeg)
        # test_io.py - tries to import libturbojpeg that we don't install (conflicts with opencv that uses libjpeg)
        # test_progressbar.py, test_timer.py - on OSX sleep(1) takes 1.1sec, so all related tests fail
        # test_image_misc.py::test_tensor2imgs - need to investigate 2/75 mismatch
        - python3 -m pytest ./tests/ -k "not ({{ (failing_tests + slow_tests)|join(' or ') }})" --ignore={{ ignored_files|join(' --ignore=') }}
        - python3 -c "import mmcv; print(mmcv.__version__)"


about:
  home: https://github.com/open-mmlab/mmcv
  summary: Foundational library for computer vision research
  description: |
    MMCV is a foundational library for computer vision research and supports many research projects.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/open-mmlab/mmcv

extra:
  recipe-maintainers:
    - weiji14
    - apatsekin
  feedstock-name: mmcv
