{% set version = "2.2.0" %}
{% set build = 2 %}

# see https://github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% endif %}

package:
  name: mmcv-recipe
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmcv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 13b2bdab6e97799177dee568efdb2ae0bb48b1dc924a8b617416ee8a392e5348
build:
  number: {{ build }}
  skip: true  # [win]

outputs:
  - name: mmcv
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
    script: build_mmcv.sh  # [not win]
    requirements:
      build:
        - cross-python_{{ target_platform }}             # [build_platform != target_platform]
        - ninja
        - numpy                                          # [build_platform != target_platform]
        - psutil
        - python                                         # [build_platform != target_platform]
        - pytorch                                        # [build_platform != target_platform]
        - pytorch ={{ pytorch }}={{ torch_proc_type }}*  # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        # this adds matching cuda requirement to run deps using __cuda package
        - {{ compiler('cuda') }}                         # [cuda_compiler_version != "None"]
        {% if cuda_major >= 12 %}
        - libcublas-dev                                  # [build_platform != target_platform]
        - libcusolver-dev                                # [build_platform != target_platform]
        - libcusparse-dev                                # [build_platform != target_platform]
        {% endif %}
      host:
        - numpy
        - pip
        - python
        - pytorch
        - pytorch ={{ pytorch }}={{ torch_proc_type }}*
        - setuptools
        {% if cuda_major >= 12 %}
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        # intentionally skipping opencv and pytorch (following upstream vendor)
        - __cuda  # [cuda_compiler_version != "None"]
        - addict
        - mmengine>=0.3.0
        - packaging
        - Pillow
        - pyyaml
        - typing_extensions
        - yapf
      run_constrained:
        # additional run constraint to the one from the (version-only) run_export;
        # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
        - pytorch =*={{ torch_proc_type }}*
    test:
      requires:
        - onnx
        - pip
        - pytest
        - pyturbojpeg
        - py-opencv
        - tifffile
        - torchvision
      imports:
        - mmcv
      source_files:
        - .dev_scripts/check_installation.py
        - tests
      commands:
        # - pip check  # disabled because mmengine on conda-forge is mmengine-lite
        - python ./.dev_scripts/check_installation.py
        - python -m pytest ./tests/
        - python -c "import mmcv; print(mmcv.__version__)"

about:
  home: https://github.com/open-mmlab/mmcv
  summary: OpenMMLab Computer Vision Foundation
  license: Apache-2.0 AND LicenseRef-NVIDIA-License
  license_file:
    - LICENSE
    - LICENSES.md
  doc_url: https://mmcv.readthedocs.io
  dev_url: https://github.com/open-mmlab/mmcv

extra:
  recipe-maintainers:
    - weiji14
    - apatsekin
  feedstock-name: mmcv
