{% set version = "2.2.0" %}
{% set build = 8 %}

# see https://github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}

package:
  name: mmcv-recipe
  version: {{ version }}

source:
  url: https://github.com/open-mmlab/mmcv/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 13b2bdab6e97799177dee568efdb2ae0bb48b1dc924a8b617416ee8a392e5348
build:
  number: {{ build }}
  skip: true  # [win]
  skip: true  # [py==313]

outputs:
  - name: mmcv
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      script_env:
        - CROSS_COMPILING=true   # [build_platform != target_platform]
        - CROSS_COMPILING=false  # [build_platform == target_platform]
    script: build_mmcv.sh  # [not win]
    requirements:
      build:
        - cross-python_{{ target_platform }}             # [build_platform != target_platform]
        - ninja
        - numpy                                          # [build_platform != target_platform]
        - psutil
        - python                                         # [build_platform != target_platform]
        - pytorch                                        # [build_platform != target_platform]
        - pytorch * {{ torch_proc_type }}*               # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        {% if cuda_compiler_version != "None" %}
        # this adds matching cuda requirement to run deps using __cuda package
        - {{ compiler('cuda') }}
        - libcublas-dev                                  # [build_platform != target_platform]
        - libcusolver-dev                                # [build_platform != target_platform]
        - libcusparse-dev                                # [build_platform != target_platform]
        {% endif %}
      host:
        - numpy
        - pip
        - python
        - pytorch
        - pytorch * {{ torch_proc_type }}*
        - setuptools
        {% if cuda_compiler_version != "None" %}
        # Ensure cuda version matches build https://github.com/conda-forge/mmcv-recipe-feedstock/issues/40
        - cuda-version {{ cuda_compiler_version }}
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        # intentionally skipping opencv and pytorch (following upstream vendor)
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
        - addict
        - mmengine >=0.3.0
        - packaging
        - Pillow
        - pyyaml
        - typing_extensions
        - yapf
      run_constrained:
        # additional run constraint to the one from the (version-only) run_export;
        # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
        - pytorch * {{ torch_proc_type }}*
    test:
      requires:
        - onnx
        - pip
        - pytest
        - pyturbojpeg
        - py-opencv
        - tifffile
        - torchvision
      imports:
        - mmcv
      source_files:
        - .dev_scripts/check_installation.py
        - tests
      commands:
        # - pip check  # disabled because mmengine on conda-forge is mmengine-lite
        - python ./.dev_scripts/check_installation.py
        # unknown osx_64 segfault on test_pixel_group
        {% set tests_to_skip = "test_pixel_group" %}
        # {% set tests_to_skip = tests_to_skip + " or test_<placeholder>" %}
        - $PYTHON -m pytest --verbose ./tests/  # [not (osx and x86_64)]
        - $PYTHON -m pytest --verbose -rxXs -k "not ({{ tests_to_skip }})" ./tests/  # [osx and x86_64]
        - python -c "import mmcv; print(mmcv.__version__)"

about:
  home: https://github.com/open-mmlab/mmcv
  summary: OpenMMLab Computer Vision Foundation
  license: Apache-2.0 AND LicenseRef-NVIDIA-License
  license_file:
    - LICENSE
    - LICENSES.md
  doc_url: https://mmcv.readthedocs.io
  dev_url: https://github.com/open-mmlab/mmcv

extra:
  recipe-maintainers:
    - apatsekin
    - das-intensity
    - weiji14
  feedstock-name: mmcv
